# Kubernetes deployment configuration for DeFAI Platform
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defai-app
  labels:
    app: defai-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: defai-app
  template:
    metadata:
      labels:
        app: defai-app
        version: v1
    spec:
      containers:
      - name: app
        image: ghcr.io/your-org/convictionfi-dapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_SUI_NETWORK
          valueFrom:
            configMapKeyRef:
              name: defai-config
              key: sui-network
        - name: NEXT_PUBLIC_RPC_URL
          valueFrom:
            secretKeyRef:
              name: defai-secrets
              key: rpc-url
        - name: NEXT_PUBLIC_ANALYTICS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: defai-config
              key: analytics-endpoint
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.next/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      securityContext:
        fsGroup: 1001

---
apiVersion: v1
kind: Service
metadata:
  name: defai-service
  labels:
    app: defai-app
spec:
  selector:
    app: defai-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: defai-config
data:
  sui-network: "testnet"
  analytics-endpoint: "/api/analytics"

---
apiVersion: v1
kind: Secret
metadata:
  name: defai-secrets
type: Opaque
data:
  # Base64 encoded values
  rpc-url: aHR0cHM6Ly9mdWxsbm9kZS50ZXN0bmV0LnN1aS5pby8=

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defai-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "10"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - defai.com
    secretName: defai-tls
  rules:
  - host: defai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: defai-service
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: defai-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: defai-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80