# Docker Compose configuration for DeFAI Platform
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUI_NETWORK=${NEXT_PUBLIC_SUI_NETWORK:-testnet}
        - NEXT_PUBLIC_ANALYTICS_ENDPOINT=${NEXT_PUBLIC_ANALYTICS_ENDPOINT}
        - NEXT_PUBLIC_RPC_URL=${NEXT_PUBLIC_RPC_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUI_NETWORK=${NEXT_PUBLIC_SUI_NETWORK:-testnet}
      - NEXT_PUBLIC_ANALYTICS_ENDPOINT=${NEXT_PUBLIC_ANALYTICS_ENDPOINT}
      - NEXT_PUBLIC_RPC_URL=${NEXT_PUBLIC_RPC_URL}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - defai-network

  # Redis for rate limiting and caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - defai-network
    command: redis-server --appendonly yes

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - defai-network

volumes:
  redis-data:

networks:
  defai-network:
    driver: bridge