[package]
name = "ConvictionFi"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
conviction_fi = "0x0"

[dev-dependencies]

[dev-addresses]
# Remove the duplicate address assignment - dev addresses will inherit from [addresses]